# Dependencies
#markdown:         kramdown
#highlighter:      rouge

excerpt_separator: <!--more-->

# Permalinks
permalink:        pretty

# Setup
title:            "Personal Development"
tagline:          "Steve Baros"
description:      "Blog about lessons learned, best practices and guidelines in personal development"
url:              https://stevebaros.me/

author:
  name:           "Stephen Barungi"
  url:            https://stevebaros.me/

paginate:          4
google_analytics:  'UA-111249059-1'
bing_seo:		       '6AB932E778FB7A41E5AE236F384FE718'
emailme:            https://twitter.com/stevebaros

github:
  repo:             https://github.com/stevebaros/blog/
#repository: RicardoNiepel/ricardoniepel.github.io

tags:

twitter_username:   stevebaros
github_username:    stevebaros
linkedin_username:  stevebaros
xing_username:      stevebaros

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  #syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
   # css_class: 'highlight'


# Set the Sass partials directory, as we're using @imports
#sass:
  #style: :expanded # You might prefer to minify using :compressed

 

# Use the following plug-ins
plugins:
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem


# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby  
